name: asl
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python==3.6.7
  - tensorflow-gpu==2.0
  - matplotlib
  - pandas
  - scikit-image
  - ipykernel
  - pip
  - pip:
    - opencv-python
    - tqdm
    - telegram-send
    - tensorflow-gpu==2.0
