# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://NicholasGoh.github.io/asl_detection/"

git_url = "https://github.com/NicholasGoh/asl_detection/tree/master/"

def custom_doc_links(name): return None
