# AUTOGENERATED! DO NOT EDIT! File to edit: 02_save_utils.ipynb (unless otherwise specified).

__all__ = ['save']

# Cell
import os

def save(save_folder, folder, model=None, fig=None):
    save_folder = os.path.join(save_folder, folder)
    os.makedirs(save_folder, exist_ok=True)
    counter = 0
    if fig:
        save_path = save_folder + f'/{folder}_%d.jpg'
        while os.path.isfile(save_path % counter):
            counter += 1
        fig.savefig(save_path % counter)
    elif model:
        save_path = save_folder + f'/{folder}_%d.h5'
        while os.path.isfile(save_path % counter):
            counter += 1
        model.save(save_path % counter)